const { contextBridge, ipcRenderer } = require("electron");

const allowedAppCommands = new Set([
  "apply_player_action",
  "bind_tunnel_to_server",
  "check_app_update",
  "check_content_updates",
  "check_server_update",
  "clear_app_cache",
  "clear_app_logs",
  "create_backup_profile",
  "create_notification_event",
  "create_profile_backup",
  "create_scheduled_task",
  "create_server_profile",
  "create_tunnel_provider",
  "create_world_backup",
  "delete_backup_profile",
  "delete_scheduled_task",
  "delete_server_backup",
  "delete_server_profile",
  "delete_tunnel_provider",
  "detect_server_version",
  "disable_installed_content",
  "enable_installed_content",
  "export_app_settings",
  "export_diagnostic_package",
  "export_server_backup",
  "export_server_profile",
  "get_app_data_folder",
  "get_app_logs_folder",
  "get_app_preferences",
  "get_bbsmc_project",
  "get_content_update_policy",
  "get_curseforge_project",
  "get_default_server_root",
  "get_modrinth_project",
  "get_notification_preferences",
  "get_performance_history",
  "get_process_summary",
  "get_server_process_status",
  "get_server_setup_status",
  "get_tunnel_provider",
  "import_app_settings",
  "import_curseforge_manual",
  "import_local_content",
  "import_modpack",
  "import_profile",
  "install_all_content_updates",
  "install_app_update",
  "install_bbsmc_public_file",
  "install_content_update",
  "install_curseforge_file",
  "install_hangar_version",
  "install_modrinth_version",
  "install_server_update",
  "list_app_logs",
  "list_backup_profiles",
  "list_bbsmc_versions",
  "list_curseforge_files",
  "list_diagnostic_runs",
  "list_hangar_versions",
  "list_installed_content",
  "list_java_runtimes",
  "list_loader_minecraft_versions",
  "list_loader_versions",
  "list_modrinth_versions",
  "list_notification_events",
  "list_players",
  "list_process_events",
  "list_scheduled_task_runs",
  "list_scheduled_tasks",
  "list_server_backups",
  "list_server_files",
  "list_server_logs",
  "list_server_profiles",
  "list_server_update_history",
  "list_tunnel_bindings",
  "list_tunnel_providers",
  "list_tunnel_statuses",
  "open_app_data_folder",
  "open_app_logs_folder",
  "open_tunnel_application",
  "plan_content_updates",
  "preview_modpack_import_command",
  "preview_profile_import",
  "read_player_lists",
  "read_server_log",
  "read_server_properties",
  "read_server_text_file",
  "request_app_quit",
  "reset_app_preferences",
  "restart_server",
  "restart_server_with_countdown",
  "restore_world_backup",
  "run_due_scheduled_tasks",
  "run_server_diagnostics",
  "sample_server_metrics",
  "save_app_preferences",
  "save_content_update_policy",
  "save_notification_preferences",
  "save_player_list",
  "save_server_properties",
  "search_bbsmc_projects",
  "search_curseforge_projects",
  "search_hangar_projects",
  "search_modrinth_projects",
  "send_server_command",
  "show_open_dialog",
  "show_save_dialog",
  "start_server",
  "stop_server",
  "unbind_tunnel_from_server",
  "uninstall_installed_content",
  "update_backup_profile",
  "update_scheduled_task",
  "update_server_profile",
  "update_tunnel_provider",
  "write_app_log",
  "write_server_text_file",
]);

contextBridge.exposeInMainWorld("mcServerManager", {
  invoke(command, args) {
    if (!allowedAppCommands.has(command)) {
      return Promise.reject(
        new Error(`Unsupported renderer command: ${String(command)}`),
      );
    }
    return ipcRenderer.invoke("app-command", command, args);
  },
  openExternalUrl(url) {
    return ipcRenderer.invoke("open-external-url", url);
  },
  windowAction(action) {
    return ipcRenderer.invoke("window-action", action);
  },
  onCloseBehaviorRequested(callback) {
    const listener = () => callback();
    ipcRenderer.on("close-behavior-requested", listener);
    return () =>
      ipcRenderer.removeListener("close-behavior-requested", listener);
  },
});
